### ISSUE TITLE
Create package structure 

### ISSUE THREAD

**Issue by blainelewis1** [CMPUT301W15T10/301-Project#64]
I'm unsure what a nice package structure for Android is. Seeing as you've had experience it'd be nice to see what has worked well for you.

**Comment by EdmondChuiHW** [comment]
It follows the Java convention: package by functionality (not screens). So an example of possible packages would be,
- model (usually pure Java, no Android resource stuff; M in MVC)
- widgets (custom views, if any; V in MVC)
- controllers (probably irrelevant to our project since most screens are static; C in MVC)
- adapters (custom list adapters, can be part of the controllers package)
- utils (common static helper methods)
- activities (activities/fragments)

Activities in Android somehow overlaps with the role of a controller, but then again Android isn't built with MVC at all (https://www.google.ca/search?client=safari&rls=en&q=mvc+site:http://developer.android.com&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=15z0VKvaL-ay8weyw4DgCw).

**Comment by EdmondChuiHW** [comment]
Actually controllers can be the database stuff (talking to local storage, network, etc.).
